# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responses.Response')),
            ],
        ),
    ]
