# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_auto_20161017_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cards', models.ManyToManyField(to='cards.Card')),
            ],
        ),
    ]
