# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_response_card'),
        ('comments', '0002_auto_20161018_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='responses.Response'),
        ),
    ]
