# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20161017_2104'),
        ('responses', '0002_auto_20161017_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cards.Card'),
        ),
    ]
